// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ParametricArt",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "ParametricArt",
            targets: ["AppModule"],
            bundleIdentifier: "me.Leite.Gabriel.GeometryArt",
            teamIdentifier: "KK45GWU9MA",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            appCategory: .education
        )
    ],
    dependencies: [
        .package(path: "../HTMLEntities"),
        .package(path: "../MathJaxSwift"),
        .package(path: "../SVGView"),
        .package(path: "../LaTeXSwiftUI")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "HTMLEntities", package: "htmlentities"),
                .product(name: "MathJaxSwift", package: "mathjaxswift"),
                .product(name: "SVGView", package: "svgview"),
                .product(name: "LaTeXSwiftUI", package: "latexswiftui")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)