// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "GeometryArt",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "GeometryArt",
            targets: ["AppModule"],
            bundleIdentifier: "me.Leite.Gabriel.GeometryArt",
            teamIdentifier: "KK45GWU9MA",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .movieReel),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/colinc86/LaTeXSwiftUI.git", .branch("main"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "LaTeXSwiftUI", package: "latexswiftui")
            ],
            path: "."
        )
    ]
)