language: swift
osx_image: xcode11.3

branches:
    only:
    - main

script:
- set -o pipefail && xcodebuild -project SVGView.xcodeproj -scheme 'SVGView' -sdk iphonesimulator13.2 ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro' | xcpretty;

notifications:
    slack: exyte:rbHEfGcQnX1drc0KNL0HVudX
